-- 1. PostGIS 확장 기능 활성화
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. 유저 테이블 (Users)
CREATE TABLE "users" (
    "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "login_id" varchar(50) UNIQUE,
    "kakao_id" BIGINT UNIQUE,             -- BIGINT로 변경
    "password_hash" varchar(255),
    "auth_type" varchar(20) DEFAULT 'LOCAL', -- 'LOCAL', 'KAKAO'
    "user_name" varchar(50) NOT NULL,
    "phone_number" varchar(20),
    "created_at" timestamptz DEFAULT (now()),
    "updated_at" timestamptz DEFAULT (now())
);

-- 3. 유저 설정 테이블 (User Settings)
CREATE TABLE "user_settings" (
    "user_id" BIGINT PRIMARY KEY REFERENCES "users" ("user_id") ON DELETE CASCADE,
    "wheelchair_type" char(1), -- 'M': 수동, 'E': 전동 등
    "max_slope_limit" numeric(4,2)
);

-- 4. 노드 테이블 (Nodes)
CREATE TABLE "nodes" (
    "node_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "geom_node" geometry(Point, 4326) NOT NULL
);
CREATE INDEX idx_nodes_geom ON nodes USING GIST (geom_node);

-- 5. 엣지 테이블 (Edges)
CREATE TABLE "edges" (
    "edge_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "source_node" BIGINT NOT NULL REFERENCES "nodes" ("node_id") ON DELETE CASCADE,
    "target_node" BIGINT NOT NULL REFERENCES "nodes" ("node_id") ON DELETE CASCADE,
    "geom_edges" geometry(LineString, 4326),
    "distance_m" numeric(10,2),
    "avg_slope_percent" numeric(5,2),
    "width_m" numeric(4,2),
    "is_accessible" boolean NOT NULL DEFAULT true,
    "safety_cost" float DEFAULT 0
);
CREATE INDEX idx_edges_geom ON edges USING GIST (geom_edges);

-- 6. 즐겨찾기 테이블 (Favorites)
CREATE TABLE "favorites" (
    "favor_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL REFERENCES "users" ("user_id") ON DELETE CASCADE,
    "favor_name" varchar(100) NOT NULL,
    "target_node_id" BIGINT NOT NULL REFERENCES "nodes" ("node_id") ON DELETE CASCADE
);

-- 7. 제보 테이블 (Reports)
CREATE TABLE "reports" (
    "report_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "edge_id" BIGINT NOT NULL REFERENCES "edges" ("edge_id") ON DELETE CASCADE,
    "user_id" BIGINT NOT NULL REFERENCES "users" ("user_id") ON DELETE CASCADE,
    "report_type" varchar(50) NOT NULL, -- 'STEEP', 'BARRIER', 'CONSTRUCTION' 등
    "content" text NOT NULL,
    "status" varchar(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    "created_at" timestamptz DEFAULT (now())
);

-- 8. 제보 이미지 테이블 (Report Images)
CREATE TABLE "report_images" (
    "report_image_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "report_id" BIGINT REFERENCES "reports" ("report_id") ON DELETE CASCADE,
    "image_url" text NOT NULL,
    "image_order" smallint DEFAULT 1,
    "created_at" timestamptz DEFAULT (now())
);

-- 9. 검증 테이블 (Verification)
CREATE TABLE "verification" (
    "verification_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "report_id" BIGINT REFERENCES "reports" ("report_id") ON DELETE CASCADE,
    "is_approved" boolean NOT NULL,
    "comment" text,
    "verified_at" timestamptz DEFAULT (now())
);