-- 1. 공간 데이터 확장 활성화
CREATE EXTENSION postgis;

-- 2. 유저 테이블 (Users)
CREATE TABLE "users" (
"user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"login_id" varchar(50) UNIQUE,
"kakao_id" varchar(50) UNIQUE NOT NULL,
"password_hash" varchar(255),
"auth_type" varchar(20) DEFAULT 'LOCAL',
"user_name" varchar(50) NOT NULL,
"phone_number" varchar(20),
"created_at" timestamptz DEFAULT (now()),
"updated_at" timestamptz DEFAULT (now())
);

-- 3. 유저 설정 테이블 (User Settings)
CREATE TABLE "user_settings" (
"user_id" bigint PRIMARY KEY,
"wheelchair_type" char(1),
"max_slope_limit" numeric(4,2)
);

-- 4. 노드 테이블 (Nodes - 길 찾기 지점)
CREATE TABLE "nodes" (
"node_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"geom_node" geometry(Point, 4326) NOT NULL
);

-- 5. 엣지 테이블 (Edges - 도로 구간)
CREATE TABLE "edges" (
"edge_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"source_node" bigint NOT NULL,
"target_node" bigint NOT NULL,
"geom_edges" geometry(LineString, 4326),
"distance_m" numeric(8,2),
"avg_slope_percent" numeric(5,2),
"width_m" numeric(4,2),
"is_accessible" boolean NOT NULL DEFAULT true,
"safety_cost" float
);

-- 6. 즐겨찾기 테이블 (Favorites)
CREATE TABLE "favorites" (
"favor_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"user_id" bigint NOT NULL,
"favor_name" varchar(100) NOT NULL,
"target_node_id" bigint NOT NULL
);

-- 7. 제보 테이블 (Reports)
CREATE TABLE "reports" (
"report_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"edge_id" bigint NOT NULL,
"user_id" bigint NOT NULL,
"report_type" varchar(50) NOT NULL,
"content" text NOT NULL,
"status" varchar(20) NOT NULL,
"created_at" timestamptz DEFAULT (now())
);

-- 8. 제보 이미지 테이블 (Report Images)
CREATE TABLE "report_images" (
"report_image_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"report_id" bigint,
"image_url" text,
"image_order" smallint,
"created_at" timestamptz DEFAULT (now())
);

-- 9. 검증 테이블 (Verification)
CREATE TABLE "verification" (
"verification_id" serial PRIMARY KEY,
"report_id" bigint,
"is_approved" boolean NOT NULL,
"comment" text,
"verified_at" timestamptz DEFAULT (now())
);

-- 10. 외래키 제약 조건 설정 (관계성 부여)
ALTER TABLE "user_settings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "favorites" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "favorites" ADD FOREIGN KEY ("target_node_id") REFERENCES "nodes" ("node_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "edges" ADD FOREIGN KEY ("source_node") REFERENCES "nodes" ("node_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "edges" ADD FOREIGN KEY ("target_node") REFERENCES "nodes" ("node_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "reports" ADD FOREIGN KEY ("edge_id") REFERENCES "edges" ("edge_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "reports" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "report_images" ADD FOREIGN KEY ("report_id") REFERENCES "reports" ("report_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "verification" ADD FOREIGN KEY ("report_id") REFERENCES "reports" ("report_id") DEFERRABLE INITIALLY IMMEDIATE;

-- 11. 공간 데이터 성능 최적화를 위한 인덱스 생성 (GiST)
CREATE INDEX idx_nodes_geom ON nodes USING GIST (geom_node);
CREATE INDEX idx_edges_geom ON edges USING GIST (geom_edges);