-- =========================================================
-- 0. 확장 기능 활성화
-- PostGIS: 공간 데이터 타입/함수 제공
-- pgRouting: 그래프 기반 최단경로 탐색 제공
-- =========================================================
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgrouting;


-- =========================================================
-- 1. 사용자 테이블
-- 로그인 정보, 사용자 기본 정보 저장
-- =========================================================
CREATE TABLE IF NOT EXISTS "users" (
    "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 사용자 PK
    "login_id" VARCHAR(50) UNIQUE,                                -- 일반 로그인 ID
    "kakao_id" BIGINT UNIQUE,                                     -- 카카오 로그인 ID
    "password_hash" VARCHAR(255),                                 -- 비밀번호 해시
    "auth_type" VARCHAR(20) DEFAULT 'LOCAL',                      -- 인증 방식 (LOCAL, KAKAO 등)
    "user_name" VARCHAR(50) NOT NULL,                             -- 사용자 이름
    "phone_number" VARCHAR(20),                                   -- 전화번호
    "created_at" TIMESTAMPTZ DEFAULT NOW(),                       -- 생성일시
    "updated_at" TIMESTAMPTZ DEFAULT NOW(),                       -- 수정일시
    "role" VARCHAR(20) DEFAULT 'ROLE_USER'                        -- 권한
);


-- =========================================================
-- 2. 사용자 설정 테이블
-- 휠체어 유형, 허용 경사도 등 사용자 맞춤 옵션 저장
-- users와 1:1 관계
-- =========================================================
CREATE TABLE IF NOT EXISTS "user_settings" (
    "user_id" BIGINT PRIMARY KEY REFERENCES "users" ("user_id") ON DELETE CASCADE, -- 사용자 PK이자 FK
    "wheelchair_type" CHAR(1),                                                      -- 휠체어 타입
    "max_slope_limit" NUMERIC(4,2) CHECK ("max_slope_limit" >= 0)                   -- 허용 최대 경사도
);


-- =========================================================
-- 3. 노드 테이블
-- 길찾기 그래프의 정점(Vertex)
-- geom_node는 각 노드의 위치 좌표(Point)
-- =========================================================
CREATE TABLE IF NOT EXISTS "nodes" (
    "node_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 노드 PK
    "geom_node" GEOMETRY(Point, 4326) NOT NULL                     -- WGS84 좌표계의 점(Point)
);

-- 공간 검색 성능 향상을 위한 GiST 인덱스
CREATE INDEX IF NOT EXISTS idx_nodes_geom ON "nodes" USING GIST ("geom_node");


-- =========================================================
-- 4. 엣지 테이블
-- 길찾기 그래프의 간선(Edge)
-- source_node -> target_node 연결
-- =========================================================
CREATE TABLE IF NOT EXISTS "edges" (
    "edge_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,          -- 엣지 PK
    "source_node" BIGINT NOT NULL REFERENCES "nodes" ("node_id") ON DELETE CASCADE, -- 시작 노드
    "target_node" BIGINT NOT NULL REFERENCES "nodes" ("node_id") ON DELETE CASCADE, -- 도착 노드

    "geom_edges" GEOMETRY(LineString, 4326) NOT NULL,                       -- 도로/경로 선형 정보
    "distance_m" NUMERIC(10,2) NOT NULL,                                    -- 거리(m)
    "avg_slope_percent" NUMERIC(5,2) NOT NULL DEFAULT 0,                    -- 평균 경사도(%)
    "width_m" NUMERIC(4,2),                                                 -- 도로 폭(m)
    "is_accessible" BOOLEAN NOT NULL DEFAULT TRUE,                          -- 접근 가능 여부
    "safety_cost" DOUBLE PRECISION NOT NULL DEFAULT 0,                      -- 추가 안전 비용(확장용)

	-- 정방향 / 역방향 비용
    "cost" DOUBLE PRECISION,
    "reverse_cost" DOUBLE PRECISION,
	
    -- 동일 노드를 자기 자신에게 연결하는 이상 데이터 방지
    CONSTRAINT chk_edges_source_target_diff CHECK ("source_node" <> "target_node"),

    -- 거리 음수 방지
    CONSTRAINT chk_edges_distance_nonnegative CHECK ("distance_m" >= 0),

    -- 폭이 입력된 경우 양수여야 함
    CONSTRAINT chk_edges_width_positive CHECK ("width_m" IS NULL OR "width_m" > 0)
);

-- 공간 인덱스
CREATE INDEX IF NOT EXISTS idx_edges_geom ON "edges" USING GIST ("geom_edges");

-- 그래프 탐색/조인 성능 향상을 위한 일반 인덱스
CREATE INDEX IF NOT EXISTS idx_edges_source ON "edges" ("source_node");
CREATE INDEX IF NOT EXISTS idx_edges_target ON "edges" ("target_node");


-- =========================================================
-- 5. 경로 비용 계산 함수
-- 거리 + 경사도 + 접근 가능 여부를 반영하여 cost를 계산
-- pgRouting에서 사용할 비용 값 생성용
-- =========================================================
CREATE OR REPLACE FUNCTION calculate_route_cost(
    distance NUMERIC,
    slope NUMERIC,
    is_accessible BOOLEAN
)
RETURNS DOUBLE PRECISION AS $$
BEGIN
    IF COALESCE(is_accessible, FALSE) = FALSE THEN
        RETURN 999999.0;
    END IF;

    IF distance IS NULL THEN
        RETURN 999999.0;
    END IF;

    IF slope IS NULL THEN
        slope := 0;
    END IF;

    -- 오르막이면 강한 패널티
    IF slope > 0 THEN
        RETURN distance * (1.0 + (POWER(slope, 2) / 10.0));
    END IF;

    -- 내리막이면 약한 패널티 또는 거의 거리 위주
    RETURN distance * (1.0 + (ABS(slope) / 20.0));
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- =========================================================
-- 6. 비용 갱신 함수
-- 정방향은 현재 slope
-- 역방향은 slope 부호 반전
-- =========================================================
CREATE OR REPLACE FUNCTION refresh_edge_costs()
RETURNS VOID AS $$
BEGIN
    UPDATE edges
    SET
        cost =
            calculate_route_cost(distance_m, avg_slope_percent, is_accessible)
            + COALESCE(safety_cost, 0),
        reverse_cost =
            calculate_route_cost(distance_m, -avg_slope_percent, is_accessible)
            + COALESCE(safety_cost, 0);
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- 7. 안전 경로 탐색 함수
-- 시작 노드와 종료 노드를 받아 pgr_dijkstra로 최적 경로를 탐색
-- 반환값:
--   seq      : 전체 결과 순서
--   path_seq : 경로 내부 순서
--   node_id  : 현재 노드
--   edge_id  : 현재 이동한 엣지
--   cost     : 현재 엣지 비용
--   agg_cost : 시작점부터 누적 비용
--   geom     : 엣지의 공간 정보(LineString)
-- =========================================================
CREATE OR REPLACE FUNCTION find_safe_path(
    start_node_id BIGINT,
    end_node_id BIGINT
)
RETURNS TABLE (
    seq INTEGER,
    path_seq INTEGER,
    node_id BIGINT,
    edge_id BIGINT,
    cost DOUBLE PRECISION,
    agg_cost DOUBLE PRECISION,
    geom GEOMETRY(LineString, 4326)
) AS $$
BEGIN
    -- 시작 노드와 종료 노드가 같으면 잘못된 호출로 보고 예외 발생
    IF start_node_id = end_node_id THEN
        RAISE EXCEPTION 'start_node_id and end_node_id must be different';
    END IF;

    RETURN QUERY
    SELECT
        d.seq::INTEGER,                 -- 전체 결과 순서
        d.path_seq::INTEGER,            -- 경로 내부 순서
        d.node::BIGINT AS node_id,      -- 현재 노드 ID
        d.edge::BIGINT AS edge_id,      -- 현재 엣지 ID
        d.cost::DOUBLE PRECISION,       -- 해당 구간 비용
        d.agg_cost::DOUBLE PRECISION,   -- 누적 비용
        e.geom_edges                    -- 엣지의 선형 geometry
    FROM pgr_dijkstra(
        '
        SELECT
            edge_id AS id,
            source_node AS source,
            target_node AS target,
            calculate_route_cost(distance_m, avg_slope_percent, is_accessible) + COALESCE(safety_cost, 0) AS cost,
        	calculate_route_cost(distance_m, -avg_slope_percent, is_accessible) + COALESCE(safety_cost, 0) AS reverse_cost
        FROM edges
        ',
        start_node_id,
        end_node_id,
        directed := TRUE
    ) AS d
    LEFT JOIN "edges" e
        ON d.edge = e.edge_id
    ORDER BY d.seq;
END;
$$ LANGUAGE plpgsql STABLE;


-- =========================================================
-- 8. 즐겨찾기 테이블
-- 사용자가 특정 노드를 즐겨찾기 지점으로 저장
-- =========================================================
CREATE TABLE IF NOT EXISTS "favorites" (
    "favor_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,         -- 즐겨찾기 PK
    "user_id" BIGINT NOT NULL REFERENCES "users" ("user_id") ON DELETE CASCADE,   -- 사용자 FK
    "favor_name" VARCHAR(100) NOT NULL,                                     -- 즐겨찾기 이름
    "target_node_id" BIGINT NOT NULL REFERENCES "nodes" ("node_id") ON DELETE CASCADE, -- 대상 노드 FK

    -- 같은 사용자가 같은 노드를 중복 즐겨찾기하는 것 방지
    CONSTRAINT uq_favorites_user_target UNIQUE ("user_id", "target_node_id")
);


-- =========================================================
-- 9. 제보 테이블
-- 경사 급함, 장애물, 공사중 등의 현장 제보 저장
-- =========================================================
CREATE TABLE IF NOT EXISTS "reports" (
    "report_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,        -- 제보 PK
    "edge_id" BIGINT NOT NULL REFERENCES "edges" ("edge_id") ON DELETE CASCADE, -- 대상 엣지 FK
    "user_id" BIGINT NOT NULL REFERENCES "users" ("user_id") ON DELETE CASCADE, -- 작성자 FK
    "report_type" VARCHAR(50) NOT NULL,                                     -- 제보 유형
    "content" TEXT NOT NULL,                                                -- 제보 내용
    "status" VARCHAR(20) DEFAULT 'PENDING'
        CHECK ("status" IN ('PENDING', 'APPROVED', 'REJECTED')),            -- 처리 상태
    "created_at" TIMESTAMPTZ DEFAULT NOW()                                  -- 생성일시
);


-- =========================================================
-- 10. 제보 이미지 테이블
-- 하나의 제보에 여러 장의 이미지 첨부 가능
-- =========================================================
CREATE TABLE IF NOT EXISTS "report_images" (
    "report_image_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 제보 이미지 PK
    "report_id" BIGINT NOT NULL REFERENCES "reports" ("report_id") ON DELETE CASCADE, -- 제보 FK
    "image_url" TEXT NOT NULL,                                              -- 이미지 URL
    "image_order" SMALLINT DEFAULT 1,                                       -- 이미지 순서
    "created_at" TIMESTAMPTZ DEFAULT NOW(),                                 -- 생성일시

    -- 이미지 순서는 1 이상만 허용
    CONSTRAINT chk_report_images_order_positive CHECK ("image_order" >= 1)
);


-- =========================================================
-- 11. 검증 테이블
-- 관리자가 제보를 승인/반려한 기록 저장
-- 한 제보당 하나의 최종 검증만 허용하고 싶다면 UNIQUE(report_id) 사용
-- =========================================================
CREATE TABLE IF NOT EXISTS "verification" (
    "verification_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 검증 PK
    "report_id" BIGINT NOT NULL UNIQUE REFERENCES "reports" ("report_id") ON DELETE CASCADE, -- 제보 FK (1:1)
    "is_approved" BOOLEAN NOT NULL,                                          -- 승인 여부
    "comment" TEXT,                                                          -- 검증 코멘트
    "verified_at" TIMESTAMPTZ DEFAULT NOW()                                  -- 검증 일시
);
